# Generated by Django 4.2.7 on 2023-11-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(max_length=100)),
                ('search_text', models.CharField(max_length=255)),
                ('results', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
